name: iforevents_segment
description: "Segment analytics integration for IForEvents - Customer data platform for unified data collection and routing."
version: 0.0.1
homepage: https://github.com/innovafour/flutter_iforevents
repository: https://github.com/innovafour/flutter_iforevents
issue_tracker: https://github.com/innovafour/flutter_iforevents/issues
documentation: https://pub.dev/documentation/iforevents_segment/latest/

environment:
  sdk: ^3.8.1
  flutter: ">=3.3.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  flutter:
    sdk: flutter
  segment_analytics: ^1.1.10
  iforevents: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
