name: iforevents_firebase
description: "Firebase Analytics integration for IForEvents - Seamless event tracking and user analytics through Firebase platform."
version: 0.0.3
homepage: https://github.com/innovafour/flutter_iforevents
repository: https://github.com/innovafour/flutter_iforevents
issue_tracker: https://github.com/innovafour/flutter_iforevents/issues
documentation: https://pub.dev/documentation/iforevents_firebase/latest/

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

dependencies:
  flutter:
    sdk: flutter
  firebase_analytics: ^12.0.0
  iforevents: ^0.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
